packages:
  - .
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.22
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.98
  '@vuepress/plugin-shiki': ^2.0.0-rc.99
  '@vuepress/theme-default': ^2.0.0-rc.101
  vuepress: ^2.0.0-rc.22
overrides:
  esbuild: ^0.25.1
onlyBuiltDependencies:
  - esbuild
