packages:
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.26
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.114
  '@vuepress/plugin-shiki': ^2.0.0-rc.114
  '@vuepress/theme-default': ^2.0.0-rc.114
  vuepress: ^2.0.0-rc.26
overrides:
  esbuild: ^0.25.10
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
