packages:
  - .
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.20
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.80
  '@vuepress/plugin-shiki': ^2.0.0-rc.86
  '@vuepress/theme-default': ^2.0.0-rc.87
  vuepress: ^2.0.0-rc.20
overrides:
  esbuild: ^0.25.1
onlyBuiltDependencies:
  - esbuild
