packages:
  - .
  - docs

catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.24
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.112
  '@vuepress/plugin-shiki': ^2.0.0-rc.112
  '@vuepress/theme-default': ^2.0.0-rc.112
  vuepress: ^2.0.0-rc.24

overrides:
  esbuild: ^0.25.9
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
