packages:
  - .
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.21
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.94
  '@vuepress/plugin-shiki': ^2.0.0-rc.94
  '@vuepress/theme-default': ^2.0.0-rc.94
  vuepress: ^2.0.0-rc.21
overrides:
  esbuild: ^0.25.1
onlyBuiltDependencies:
  - esbuild
