packages:
  - .
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.23
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.103
  '@vuepress/plugin-shiki': ^2.0.0-rc.103
  '@vuepress/theme-default': ^2.0.0-rc.103
  vuepress: ^2.0.0-rc.23
overrides:
  esbuild: ^0.25.1
onlyBuiltDependencies:
  - esbuild
