catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.20
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.80
  '@vuepress/plugin-shiki': ^2.0.0-rc.82
  '@vuepress/theme-default': ^2.0.0-rc.82
  vuepress: ^2.0.0-rc.20
onlyBuiltDependencies:
  - esbuild
overrides:
  esbuild: ^0.25.0
packages:
  - .
  - docs
