packages:
  - .
  - docs

catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.24
  '@vuepress/plugin-google-analytics': ^2.0.0-rc.107
  '@vuepress/plugin-shiki': ^2.0.0-rc.110
  '@vuepress/theme-default': ^2.0.0-rc.110
  vuepress: ^2.0.0-rc.24

overrides:
  esbuild: ^0.25.5
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
